language: node_js
node_js:
  - "8.11"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - cd functions && npm install

script:
  - ng build --prod

deploy:
  provider: firebase
  token:
    secure: "1/BVwrl9RQmXf9cPaHkwRJCneqDYVudle0BkdjNxQMIGQ"

notifications:
  email:
    on_failure: change
    on_success: change

cache:
  directories:
    - "node_modules"
    - "functions/node_modules"